---
apiVersion: v1
kind: Service
metadata:
  name: javaweb-calculator-service
  labels:
    app: javaweb-calculator
spec:
  selector:
    app: javaweb-calculator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
