apiVersion: v1
kind: Pod
metadata:
  name: javaweb3-k8s-pod
spec:
  containers:
  - name: apache-tomcat
    image: apache-tomcat  # Replace with your actual image name
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
