---
apiVersion: v1
kind: Service
metadata:
  name: javaweb3-k8s-service
  labels:
    app: javaweb3-k8s
spec:
  type: ClusterIP
  selector:
    app: javaweb3-k8s
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: httpd



