apiVersion: v1
kind: Pod
metadata:
  name: javaweb3-k8s-pod
spec:
  containers:
  - name: apache-tomcat
    image: httpd
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "4"
        memory: "512Mi"
      requests:
        cpu: "4"
        memory: "256Mi"