apiVersion: v1
kind: Deployment
metadata:
  name: javaweb3-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaweb3-k8s-nexus
  template:
    metadata:
      labels:
        app: javaweb3-k8s
    spec:
      containers:
      - name: nexus
        image: binary-nexus
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 2