apiVersion: v1
kind: Deployment
metadata:
  name: k8s-javaweb3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-javaweb3
  template:
    metadata:
      labels:
        app: javaweb3-k8s
    spec:
      containers:
      - name: k8s-javaweb3-container
        image: beautykemefa/javaweb3-k8s:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 2