---
apiVersion: v1
kind: Service
metadata:
  name: javaweb3-k8s-service
  labels:
    app: javaweb3-k8s
spec:
  type: NodePort
  selector:
    app: javaweb3-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http



