apiVersion: apps/v1
kind: Deployment
metadata:
  name: Javaweb3-K8S
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Javaweb3-K8S
  template:
    metadata:
      labels:
        app: Javaweb3-K8S
    spec:
      containers:
      - name: javaweb-calculator
        image: beautykemefa/javaweb3-K83:latest
        ports:
        - containerPort: 8020
        resources:
          limits:
            cpu: "0.5"  # Adjust as needed
            memory: "512Mi"  # Adjust as needed
          requests:
            cpu: "0.2"  # Adjust as needed
            memory: "256Mi"  # Adjust as needed
